config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :links do 
    get :show_all_tags, on: :collection
    get :show_link_by_tag_name, on: :collection
  end 
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'links#index'
end

app/models/link.rb
class Link
  include Mongoid::Document
  field :link_text, type: String
  field :tags, type: String
  field :descriptio, type: String

  embedded_in :user

  validates :link_text, presence: true,
                    length: { minimum: 4 }
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
  embeds_many :links

  accepts_nested_attributes_for :links
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, exept: [:index]

  def index
    if user_signed_in?
      @links = current_user.links
    end
  end

  def new
    @link = current_user.links.build
  end

  def edit
    @link = current_user.links.find(link_id_params)
  end

  def create
    @link = current_user.links.new(link_params)
    
    if @link.save
      redirect_to links_path
    else 
      render 'new'
    end
  end

  def update
    @link = current_user.links.find(link_id_params)

    if @link.update_attributes(link_params)
      redirect_to links_path
    else 
      render 'edit'
    end
  end

  def destroy
    @link = current_user.links.find(link_id_params)
    @link.destroy
    
    redirect_to links_path
  end

  def show_all_tags
    @tag = []

    tags = current_user.links
    tagMass = []

    tags.each do |t|
      tagMass += t.tags.split(',')
    end

    tagMass.each do |t|
      if @tag.exclude? t
          @tag << t
      end
    end
  end

  def show_link_by_tag_name
      tags = current_user.links
      @tag = tag_params
      @links = []

      tags.each do |t|
        if t.tags.include? @tag
          @links << t
        end
      end
  end

  private
    def link_params
      params.require(:link).permit(:link_text, :tags, :descriptio)
    end

    def link_id_params
      return params[:id]
    end 

    def tag_params 
      return params[:tags]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Test
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    -if !user_signed_in?
      = link_to 'Sign in', new_user_session_path
      = link_to 'Sing up', new_user_registration_path
      %h1= 'You must sign in to working!'

    -elsif user_signed_in?
      = current_user.email
      %br= link_to 'Sign out', destroy_user_session_path, method: 'delete'

    = yield

app/views/links/_form.html.haml
= simple_form_for(@link) do |f|
  - if @link.errors.any?
    #error_explanation
      %h2
        = pluralize(@link.errors.count, "error")
        prohibited
        this link from being saved:
      %ul
        - @link.errors.full_messages.each do |msg|
          %li= msg

  .form-inputs
    = f.label :link_text, 'Link'
    = f.text_field :link_text
    = f.label :tags, 'Tags (separated by coma)'
    = f.text_field :tags
    = f.label :descriptio, 'Description'
    = f.text_area :descriptio
  .form-actions
    = f.button :submit, 'Confirm'

app/views/links/edit.html.haml
%h1 Editing link

= render 'form'

= link_to 'Back', links_path

app/views/links/index.html.haml
%h1 Listing links

%table
  %thead
    %tr
      %th Link text
      %th Tags
      %th Description
      %th
      %th
      %th

  %tbody
    - @links.each do |link|
      %tr
        %td= link_to link.link_text, 'http://' + link.link_text
        %td= link.tags
        %td= link.descriptio
        %td= link_to 'Edit', edit_link_path(link)
        %td= link_to 'Destroy', link, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Link', new_link_path
= link_to 'Show all tags', show_all_tags_links_path

app/views/links/new.html.haml
%h1 New link

= render 'form'

= link_to 'Back', links_path

app/views/links/show_all_tags.html.haml
%h1 Listing tags

- @tag.each do |t|
    = link_to t, '/links/show_link_by_tag_name?tags=' + t
    %br

%br

= link_to 'Back', links_path

app/views/links/show_link_by_tag_name.html.haml
%h1= 'Links with tag: \' ' + @tag + ' \''

%table
  %thead
    %tr
      %th{ :width => '200px', :align => 'left' } Link text
      %th{ :width => '300px', :align => 'left' } Description
      %th{ :width => '300px', :align => 'left' } tags

  %tbody
    - @links.each do |link|
      %tr
        %td= link.link_text
        %td= link.descriptio
        %td= link.tags

%br

= link_to 'Back', show_all_tags_links_path
= link_to 'Home', links_path